defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-paginate
  - jekyll-octicons
  - jekyll-stickyposts

paginate: 30
paginate_path: "/blog/page:num/"

repository:  "trusty-patches-mint/trusty-patches-mint.github.io" 